package main

import (
	"MusicLeCLI/state"
	"MusicLeCLI/ui"
)

// TrFor returns the translation for key in the given language (English
// fallback, then the raw key). Unlike Tr it never reads the active language,
// so it can measure strings of every language for fixed-size layouts.
func TrFor(lang state.Language, key string) string {
	if m, ok := allTranslations[key]; ok {
		if t, ok := m[lang]; ok && t != "" {
			return t
		}
		if t, ok := m[state.LangEnglish]; ok && t != "" {
			return t
		}
	}
	if v, ok := enFallback[key]; ok {
		return v
	}
	return key
}

// maxTrWidth returns the widest translation of key across all 11 languages,
// measured in display cells. Use it to size buttons/boxes once so switching
// language never moves them.
func maxTrWidth(key string) int {
	max := 0
	for _, l := range state.AllLanguages() {
		if w := ui.TextWidth(TrFor(l, key)); w > max {
			max = w
		}
	}
	return max
}

// Tr returns the translation for key in the current language.
func Tr(key string) string {
	m, ok := allTranslations[key]
	if !ok {
		if v, ok := enFallback[key]; ok {
			return v
		}
		return key
	}
	lang := state.Current.Language
	if t, ok := m[lang]; ok && t != "" {
		return t
	}
	if t, ok := m[state.LangEnglish]; ok && t != "" {
		return t
	}
	if v, ok := enFallback[key]; ok {
		return v
	}
	return key
}

// enFallback keeps the original English strings so Tr never returns a raw key
// even if a translation entry is missing a language.
var enFallback = map[string]string{
	"nav.home":      "Home",
	"nav.downloads": "Downloads",
	"nav.profile":   "Profile",
	"nav.playlist":  "Playlist",
	"nav.general":   "General",
}

var allTranslations = map[string]map[state.Language]string{

	// ── Language names (how each language is called in each UI language) ──
	"lang.en": {
		state.LangEnglish:    "English",
		state.LangTurkish:    "İngilizce",
		state.LangSpanish:    "inglés",
		state.LangGerman:     "Englisch",
		state.LangFrench:     "anglais",
		state.LangArabic:     "الإنجليزية",
		state.LangPortuguese: "inglês",
		state.LangChinese:    "英语",
		state.LangJapanese:   "英語",
		state.LangItalian:    "inglese",
		state.LangRussian:    "английский",
	},
	"lang.tr": {
		state.LangEnglish:    "Turkish",
		state.LangTurkish:    "Türkçe",
		state.LangSpanish:    "turco",
		state.LangGerman:     "Türkisch",
		state.LangFrench:     "turc",
		state.LangArabic:     "التركية",
		state.LangPortuguese: "turco",
		state.LangChinese:    "土耳其语",
		state.LangJapanese:   "トルコ語",
		state.LangItalian:    "turco",
		state.LangRussian:    "турецкий",
	},
	"lang.es": {
		state.LangEnglish:    "Spanish",
		state.LangTurkish:    "İspanyolca",
		state.LangSpanish:    "español",
		state.LangGerman:     "Spanisch",
		state.LangFrench:     "espagnol",
		state.LangArabic:     "الإسبانية",
		state.LangPortuguese: "espanhol",
		state.LangChinese:    "西班牙语",
		state.LangJapanese:   "スペイン語",
		state.LangItalian:    "spagnolo",
		state.LangRussian:    "испанский",
	},
	"lang.de": {
		state.LangEnglish:    "German",
		state.LangTurkish:    "Almanca",
		state.LangSpanish:    "alemán",
		state.LangGerman:     "Deutsch",
		state.LangFrench:     "allemand",
		state.LangArabic:     "الألمانية",
		state.LangPortuguese: "alemão",
		state.LangChinese:    "德语",
		state.LangJapanese:   "ドイツ語",
		state.LangItalian:    "tedesco",
		state.LangRussian:    "немецкий",
	},
	"lang.fr": {
		state.LangEnglish:    "French",
		state.LangTurkish:    "Fransızca",
		state.LangSpanish:    "francés",
		state.LangGerman:     "Französisch",
		state.LangFrench:     "français",
		state.LangArabic:     "الفرنسية",
		state.LangPortuguese: "francês",
		state.LangChinese:    "法语",
		state.LangJapanese:   "フランス語",
		state.LangItalian:    "francese",
		state.LangRussian:    "французский",
	},
	"lang.ar": {
		state.LangEnglish:    "Arabic",
		state.LangTurkish:    "Arapça",
		state.LangSpanish:    "árabe",
		state.LangGerman:     "Arabisch",
		state.LangFrench:     "arabe",
		state.LangArabic:     "العربية",
		state.LangPortuguese: "árabe",
		state.LangChinese:    "阿拉伯语",
		state.LangJapanese:   "アラビア語",
		state.LangItalian:    "arabo",
		state.LangRussian:    "арабский",
	},
	"lang.pt": {
		state.LangEnglish:    "Portuguese",
		state.LangTurkish:    "Portekizce",
		state.LangSpanish:    "portugués",
		state.LangGerman:     "Portugiesisch",
		state.LangFrench:     "portugais",
		state.LangArabic:     "البرتغالية",
		state.LangPortuguese: "português",
		state.LangChinese:    "葡萄牙语",
		state.LangJapanese:   "ポルトガル語",
		state.LangItalian:    "portoghese",
		state.LangRussian:    "португальский",
	},
	"lang.zh": {
		state.LangEnglish:    "Chinese",
		state.LangTurkish:    "Çince",
		state.LangSpanish:    "chino",
		state.LangGerman:     "Chinesisch",
		state.LangFrench:     "chinois",
		state.LangArabic:     "الصينية",
		state.LangPortuguese: "chinês",
		state.LangChinese:    "中文",
		state.LangJapanese:   "中国語",
		state.LangItalian:    "cinese",
		state.LangRussian:    "китайский",
	},
	"lang.ja": {
		state.LangEnglish:    "Japanese",
		state.LangTurkish:    "Japonca",
		state.LangSpanish:    "japonés",
		state.LangGerman:     "Japanisch",
		state.LangFrench:     "japonais",
		state.LangArabic:     "اليابانية",
		state.LangPortuguese: "japonês",
		state.LangChinese:    "日语",
		state.LangJapanese:   "日本語",
		state.LangItalian:    "giapponese",
		state.LangRussian:    "японский",
	},
	"lang.it": {
		state.LangEnglish:    "Italian",
		state.LangTurkish:    "İtalyanca",
		state.LangSpanish:    "italiano",
		state.LangGerman:     "Italienisch",
		state.LangFrench:     "italien",
		state.LangArabic:     "الإيطالية",
		state.LangPortuguese: "italiano",
		state.LangChinese:    "意大利语",
		state.LangJapanese:   "イタリア語",
		state.LangItalian:    "italiano",
		state.LangRussian:    "итальянский",
	},
	"lang.ru": {
		state.LangEnglish:    "Russian",
		state.LangTurkish:    "Rusça",
		state.LangSpanish:    "ruso",
		state.LangGerman:     "Russisch",
		state.LangFrench:     "russe",
		state.LangArabic:     "الروسية",
		state.LangPortuguese: "russo",
		state.LangChinese:    "俄语",
		state.LangJapanese:   "ロシア語",
		state.LangItalian:    "russo",
		state.LangRussian:    "русский",
	},

	// ── Navigation ────────────────────────────────────────────────
	"nav.home": {
		state.LangEnglish:    "Home",
		state.LangTurkish:    "Ana Sayfa",
		state.LangSpanish:    "Inicio",
		state.LangGerman:     "Startseite",
		state.LangFrench:     "Accueil",
		state.LangArabic:     "الرئيسية",
		state.LangPortuguese: "Início",
		state.LangChinese:    "首页",
		state.LangJapanese:   "ホーム",
		state.LangItalian:    "Home",
		state.LangRussian:    "Главная",
	},
	"nav.downloads": {
		state.LangEnglish:    "Downloads",
		state.LangTurkish:    "İndirilenler",
		state.LangSpanish:    "Descargas",
		state.LangGerman:     "Downloads",
		state.LangFrench:     "Téléchargements",
		state.LangArabic:     "التنزيلات",
		state.LangPortuguese: "Downloads",
		state.LangChinese:    "下载",
		state.LangJapanese:   "ダウンロード",
		state.LangItalian:    "Download",
		state.LangRussian:    "Загрузки",
	},
	"nav.profile": {
		state.LangEnglish:    "Profile",
		state.LangTurkish:    "Profil",
		state.LangSpanish:    "Perfil",
		state.LangGerman:     "Profil",
		state.LangFrench:     "Profil",
		state.LangArabic:     "الملف الشخصي",
		state.LangPortuguese: "Perfil",
		state.LangChinese:    "个人资料",
		state.LangJapanese:   "プロフィール",
		state.LangItalian:    "Profilo",
		state.LangRussian:    "Профиль",
	},
	"nav.playlist": {
		state.LangEnglish:    "Playlist",
		state.LangTurkish:    "Çalma Listesi",
		state.LangSpanish:    "Lista de reproducción",
		state.LangGerman:     "Playlist",
		state.LangFrench:     "Playlist",
		state.LangArabic:     "قائمة التشغيل",
		state.LangPortuguese: "Playlist",
		state.LangChinese:    "播放列表",
		state.LangJapanese:   "プレイリスト",
		state.LangItalian:    "Playlist",
		state.LangRussian:    "Плейлист",
	},
	"nav.general": {
		state.LangEnglish:    "General",
		state.LangTurkish:    "Genel",
		state.LangSpanish:    "General",
		state.LangGerman:     "Allgemein",
		state.LangFrench:     "Général",
		state.LangArabic:     "عام",
		state.LangPortuguese: "Geral",
		state.LangChinese:    "通用",
		state.LangJapanese:   "一般",
		state.LangItalian:    "Generali",
		state.LangRussian:    "Общие",
	},

	// ── Settings / General tabs ───────────────────────────────────
	"settings.title": {
		state.LangEnglish:    "General Settings",
		state.LangTurkish:    "Genel Ayarlar",
		state.LangSpanish:    "Ajustes generales",
		state.LangGerman:     "Allgemeine Einstellungen",
		state.LangFrench:     "Paramètres généraux",
		state.LangArabic:     "الإعدادات العامة",
		state.LangPortuguese: "Configurações gerais",
		state.LangChinese:    "常规设置",
		state.LangJapanese:   "一般設定",
		state.LangItalian:    "Impostazioni generali",
		state.LangRussian:    "Общие настройки",
	},
	"tab.theme": {
		state.LangEnglish:    "Theme",
		state.LangTurkish:    "Tema",
		state.LangSpanish:    "Tema",
		state.LangGerman:     "Theme",
		state.LangFrench:     "Thème",
		state.LangArabic:     "السمة",
		state.LangPortuguese: "Tema",
		state.LangChinese:    "主题",
		state.LangJapanese:   "テーマ",
		state.LangItalian:    "Tema",
		state.LangRussian:    "Тема",
	},
	"tab.language": {
		state.LangEnglish:    "Language",
		state.LangTurkish:    "Dil",
		state.LangSpanish:    "Idioma",
		state.LangGerman:     "Sprache",
		state.LangFrench:     "Langue",
		state.LangArabic:     "اللغة",
		state.LangPortuguese: "Idioma",
		state.LangChinese:    "语言",
		state.LangJapanese:   "言語",
		state.LangItalian:    "Lingua",
		state.LangRussian:    "Язык",
	},
	"tab.sound": {
		state.LangEnglish:    "Sound",
		state.LangTurkish:    "Ses",
		state.LangSpanish:    "Sonido",
		state.LangGerman:     "Ton",
		state.LangFrench:     "Son",
		state.LangArabic:     "الصوت",
		state.LangPortuguese: "Som",
		state.LangChinese:    "声音",
		state.LangJapanese:   "サウンド",
		state.LangItalian:    "Audio",
		state.LangRussian:    "Звук",
	},
	"tab.extras": {
		state.LangEnglish:    "Extras",
		state.LangTurkish:    "Ekstralar",
		state.LangSpanish:    "Extras",
		state.LangGerman:     "Extras",
		state.LangFrench:     "Extras",
		state.LangArabic:     "إضافات",
		state.LangPortuguese: "Extras",
		state.LangChinese:    "附加功能",
		state.LangJapanese:   "追加機能",
		state.LangItalian:    "Extra",
		state.LangRussian:    "Дополнительно",
	},
	"tab.policies": {
		state.LangEnglish:    "Policies",
		state.LangTurkish:    "Politikalar",
		state.LangSpanish:    "Políticas",
		state.LangGerman:     "Richtlinien",
		state.LangFrench:     "Politiques",
		state.LangArabic:     "السياسات",
		state.LangPortuguese: "Políticas",
		state.LangChinese:    "政策",
		state.LangJapanese:   "ポリシー",
		state.LangItalian:    "Politiche",
		state.LangRussian:    "Правила",
	},
	"tab.about": {
		state.LangEnglish:    "About",
		state.LangTurkish:    "Hakkında",
		state.LangSpanish:    "Acerca de",
		state.LangGerman:     "Über",
		state.LangFrench:     "À propos",
		state.LangArabic:     "حول",
		state.LangPortuguese: "Sobre",
		state.LangChinese:    "关于",
		state.LangJapanese:   "について",
		state.LangItalian:    "Info",
		state.LangRussian:    "О приложении",
	},
	"sound.no_devices": {
		state.LangEnglish:    "No output devices detected",
		state.LangTurkish:    "Çıkış cihazı bulunamadı",
		state.LangSpanish:    "No se detectaron dispositivos de salida",
		state.LangGerman:     "Keine Ausgabegeräte gefunden",
		state.LangFrench:     "Aucun périphérique de sortie détecté",
		state.LangArabic:     "لم يتم اكتشاف أجهزة إخراج",
		state.LangPortuguese: "Nenhum dispositivo de saída detectado",
		state.LangChinese:    "未检测到输出设备",
		state.LangJapanese:   "出力デバイスが見つかりません",
		state.LangItalian:    "Nessun dispositivo di output rilevato",
		state.LangRussian:    "Устройства вывода не найдены",
	},
	"sound.volume_limit": {
		state.LangEnglish:    "Volume limit",
		state.LangTurkish:    "Ses limiti",
		state.LangSpanish:    "Límite de volumen",
		state.LangGerman:     "Lautstärkebegrenzung",
		state.LangFrench:     "Limite de volume",
		state.LangArabic:     "حد الصوت",
		state.LangPortuguese: "Limite de volume",
		state.LangChinese:    "音量限制",
		state.LangJapanese:   "音量制限",
		state.LangItalian:    "Limite volume",
		state.LangRussian:    "Ограничение громкости",
	},
	"sound.hint": {
		state.LangEnglish:    "[↑↓] Device  [←→] Limit  [Enter] Save",
		state.LangTurkish:    "[↑↓] Cihaz  [←→] Limit  [Enter] Kaydet",
		state.LangSpanish:    "[↑↓] Dispositivo  [←→] Límite  [Enter] Guardar",
		state.LangGerman:     "[↑↓] Gerät  [←→] Limit  [Enter] Speichern",
		state.LangFrench:     "[↑↓] Appareil  [←→] Limite  [Enter] Enregistrer",
		state.LangArabic:     "[↑↓] الجهاز  [←→] الحد  [Enter] حفظ",
		state.LangPortuguese: "[↑↓] Dispositivo  [←→] Limite  [Enter] Salvar",
		state.LangChinese:    "[↑↓] 设备  [←→] 限制  [Enter] 保存",
		state.LangJapanese:   "[↑↓] デバイス  [←→] 制限  [Enter] 保存",
		state.LangItalian:    "[↑↓] Dispositivo  [←→] Limite  [Enter] Salva",
		state.LangRussian:    "[↑↓] Устройство  [←→] Лимит  [Enter] Сохранить",
	},
	"settings.f3_hint": {
		state.LangEnglish:    "[F3] switch tab",
		state.LangTurkish:    "[F3] sekme değiştir",
		state.LangSpanish:    "[F3] cambiar pestaña",
		state.LangGerman:     "[F3] Tab wechseln",
		state.LangFrench:     "[F3] changer d'onglet",
		state.LangArabic:     "[F3] تبديل التبويب",
		state.LangPortuguese: "[F3] alternar aba",
		state.LangChinese:    "[F3] 切换标签页",
		state.LangJapanese:   "[F3] タブ切替",
		state.LangItalian:    "[F3] cambia scheda",
		state.LangRussian:    "[F3] сменить вкладку",
	},
	"settings.select_hint": {
		state.LangEnglish:    "[↑↓] Change  [Enter] Apply  [Tab] Leave",
		state.LangTurkish:    "[↑↓] Değiştir  [Enter] Uygula  [Tab] Çık",
		state.LangSpanish:    "[↑↓] Cambiar  [Enter] Aplicar  [Tab] Salir",
		state.LangGerman:     "[↑↓] Ändern  [Enter] Anwenden  [Tab] Verlassen",
		state.LangFrench:     "[↑↓] Changer  [Enter] Appliquer  [Tab] Quitter",
		state.LangArabic:     "[↑↓] تغيير  [Enter] تطبيق  [Tab] مغادرة",
		state.LangPortuguese: "[↑↓] Alterar  [Enter] Aplicar  [Tab] Sair",
		state.LangChinese:    "[↑↓] 更改  [Enter] 应用  [Tab] 离开",
		state.LangJapanese:   "[↑↓] 変更  [Enter] 適用  [Tab] 戻る",
		state.LangItalian:    "[↑↓] Cambia  [Enter] Applica  [Tab] Esci",
		state.LangRussian:    "[↑↓] Изменить  [Enter] Применить  [Tab] Выйти",
	},

	// ── Common ────────────────────────────────────────────────────
	"common.coming_soon": {
		state.LangEnglish:    "Coming soon",
		state.LangTurkish:    "Yakında",
		state.LangSpanish:    "Próximamente",
		state.LangGerman:     "Demnächst",
		state.LangFrench:     "Bientôt",
		state.LangArabic:     "قريباً",
		state.LangPortuguese: "Em breve",
		state.LangChinese:    "即将推出",
		state.LangJapanese:   "近日公開",
		state.LangItalian:    "Prossimamente",
		state.LangRussian:    "Скоро",
	},
	"common.no_playlist": {
		state.LangEnglish:    "No playlist selected",
		state.LangTurkish:    "Çalma listesi seçilmedi",
		state.LangSpanish:    "Ninguna lista seleccionada",
		state.LangGerman:     "Keine Playlist ausgewählt",
		state.LangFrench:     "Aucune playlist sélectionnée",
		state.LangArabic:     "لم يتم اختيار قائمة تشغيل",
		state.LangPortuguese: "Nenhuma playlist selecionada",
		state.LangChinese:    "未选择播放列表",
		state.LangJapanese:   "プレイリスト未選択",
		state.LangItalian:    "Nessuna playlist selezionata",
		state.LangRussian:    "Плейлист не выбран",
	},

	// ── Download tab ───────────────────────────────────────────────
	"dl.title": {
		state.LangEnglish:    "Music Download",
		state.LangTurkish:    "Müzik İndirme",
		state.LangSpanish:    "Descarga de música",
		state.LangGerman:     "Musik-Download",
		state.LangFrench:     "Téléchargement de musique",
		state.LangArabic:     "تنزيل الموسيقى",
		state.LangPortuguese: "Download de música",
		state.LangChinese:    "音乐下载",
		state.LangJapanese:   "音楽ダウンロード",
		state.LangItalian:    "Download musica",
		state.LangRussian:    "Загрузка музыки",
	},
	"dl.spotify_url": {
		state.LangEnglish:    "Spotify URL (track/playlist):",
		state.LangTurkish:    "Spotify URL (parça/çalma listesi):",
		state.LangSpanish:    "URL de Spotify (canción/lista):",
		state.LangGerman:     "Spotify-URL (Titel/Playlist):",
		state.LangFrench:     "URL Spotify (morceau/playlist) :",
		state.LangArabic:     "رابط سبوتيفاي (مقطع/قائمة):",
		state.LangPortuguese: "URL do Spotify (faixa/playlist):",
		state.LangChinese:    "Spotify链接（单曲/歌单）：",
		state.LangJapanese:   "Spotify URL（曲/プレイリスト）：",
		state.LangItalian:    "URL Spotify (brano/playlist):",
		state.LangRussian:    "URL Spotify (трек/плейлист):",
	},
	"dl.youtube_url": {
		state.LangEnglish:    "YouTube URL:",
		state.LangTurkish:    "YouTube URL:",
		state.LangSpanish:    "URL de YouTube:",
		state.LangGerman:     "YouTube-URL:",
		state.LangFrench:     "URL YouTube :",
		state.LangArabic:     "رابط يوتيوب:",
		state.LangPortuguese: "URL do YouTube:",
		state.LangChinese:    "YouTube链接：",
		state.LangJapanese:   "YouTube URL:",
		state.LangItalian:    "URL YouTube:",
		state.LangRussian:    "URL YouTube:",
	},
	"dl.btn_playlist": {
		state.LangEnglish:    "+ Playlist",
		state.LangTurkish:    "+ Çalma Listesi",
		state.LangSpanish:    "+ Lista",
		state.LangGerman:     "+ Playlist",
		state.LangFrench:     "+ Playlist",
		state.LangArabic:     "+ قائمة تشغيل",
		state.LangPortuguese: "+ Playlist",
		state.LangChinese:    "+ 歌单",
		state.LangJapanese:   "+ プレイリスト",
		state.LangItalian:    "+ Playlist",
		state.LangRussian:    "+ Плейлист",
	},
	"dl.btn_music": {
		state.LangEnglish:    "+ Music",
		state.LangTurkish:    "+ Müzik",
		state.LangSpanish:    "+ Música",
		state.LangGerman:     "+ Musik",
		state.LangFrench:     "+ Musique",
		state.LangArabic:     "+ موسيقى",
		state.LangPortuguese: "+ Música",
		state.LangChinese:    "+ 音乐",
		state.LangJapanese:   "+ 音楽",
		state.LangItalian:    "+ Musica",
		state.LangRussian:    "+ Музыка",
	},
	"dl.btn_download": {
		state.LangEnglish:    "v Download",
		state.LangTurkish:    "v İndir",
		state.LangSpanish:    "v Descargar",
		state.LangGerman:     "v Herunterladen",
		state.LangFrench:     "v Télécharger",
		state.LangArabic:     "v تنزيل",
		state.LangPortuguese: "v Baixar",
		state.LangChinese:    "v 下载",
		state.LangJapanese:   "v ダウンロード",
		state.LangItalian:    "v Scarica",
		state.LangRussian:    "v Скачать",
	},
	"dl.no_playlists": {
		state.LangEnglish:    "(no playlists)",
		state.LangTurkish:    "(çalma listesi yok)",
		state.LangSpanish:    "(sin listas)",
		state.LangGerman:     "(keine Playlists)",
		state.LangFrench:     "(aucune playlist)",
		state.LangArabic:     "(لا توجد قوائم)",
		state.LangPortuguese: "(sem playlists)",
		state.LangChinese:    "（无歌单）",
		state.LangJapanese:   "（プレイリストなし）",
		state.LangItalian:    "(nessuna playlist)",
		state.LangRussian:    "(нет плейлистов)",
	},
	"dl.enter_url": {
		state.LangEnglish:    "Enter a URL first",
		state.LangTurkish:    "Önce bir URL girin",
		state.LangSpanish:    "Introduce una URL primero",
		state.LangGerman:     "Geben Sie zuerst eine URL ein",
		state.LangFrench:     "Entrez d'abord une URL",
		state.LangArabic:     "أدخل رابطاً أولاً",
		state.LangPortuguese: "Digite uma URL primeiro",
		state.LangChinese:    "请先输入链接",
		state.LangJapanese:   "まずURLを入力してください",
		state.LangItalian:    "Inserisci prima un URL",
		state.LangRussian:    "Сначала введите URL",
	},
	"dl.invalid_url": {
		state.LangEnglish:    "Invalid URL",
		state.LangTurkish:    "Geçersiz URL",
		state.LangSpanish:    "URL no válida",
		state.LangGerman:     "Ungültige URL",
		state.LangFrench:     "URL invalide",
		state.LangArabic:     "رابط غير صالح",
		state.LangPortuguese: "URL inválida",
		state.LangChinese:    "无效链接",
		state.LangJapanese:   "無効なURL",
		state.LangItalian:    "URL non valido",
		state.LangRussian:    "Недействительный URL",
	},
	"dl.session_ok": {
		state.LangEnglish:    "OK",
		state.LangTurkish:    "Başarılı",
		state.LangSpanish:    "OK",
		state.LangGerman:     "OK",
		state.LangFrench:     "OK",
		state.LangArabic:     "تم",
		state.LangPortuguese: "OK",
		state.LangChinese:    "成功",
		state.LangJapanese:   "OK",
		state.LangItalian:    "OK",
		state.LangRussian:    "ОК",
	},
	"dl.session_failed": {
		state.LangEnglish:    "failed",
		state.LangTurkish:    "başarısız",
		state.LangSpanish:    "fallido",
		state.LangGerman:     "fehlgeschlagen",
		state.LangFrench:     "échec",
		state.LangArabic:     "فشل",
		state.LangPortuguese: "falhou",
		state.LangChinese:    "失败",
		state.LangJapanese:   "失敗",
		state.LangItalian:    "fallito",
		state.LangRussian:    "не удалось",
	},
	"dl.session_summary": {
		state.LangEnglish:    "Session: %d %s, %d %s",
		state.LangTurkish:    "Oturum: %d %s, %d %s",
		state.LangSpanish:    "Sesión: %d %s, %d %s",
		state.LangGerman:     "Sitzung: %d %s, %d %s",
		state.LangFrench:     "Session : %d %s, %d %s",
		state.LangArabic:     "الجلسة: %d %s، %d %s",
		state.LangPortuguese: "Sessão: %d %s, %d %s",
		state.LangChinese:    "本次：%d %s，%d %s",
		state.LangJapanese:   "セッション: %d %s、%d %s",
		state.LangItalian:    "Sessione: %d %s, %d %s",
		state.LangRussian:    "Сессия: %d %s, %d %s",
	},
	"dl.downloading": {
		state.LangEnglish:    "downloading",
		state.LangTurkish:    "indiriliyor",
		state.LangSpanish:    "descargando",
		state.LangGerman:     "wird heruntergeladen",
		state.LangFrench:     "téléchargement",
		state.LangArabic:     "جارٍ التنزيل",
		state.LangPortuguese: "baixando",
		state.LangChinese:    "下载中",
		state.LangJapanese:   "ダウンロード中",
		state.LangItalian:    "download in corso",
		state.LangRussian:    "загрузка",
	},
	"dl.complete": {
		state.LangEnglish:    "Download complete",
		state.LangTurkish:    "İndirme tamamlandı",
		state.LangSpanish:    "Descarga completa",
		state.LangGerman:     "Download abgeschlossen",
		state.LangFrench:     "Téléchargement terminé",
		state.LangArabic:     "اكتمل التنزيل",
		state.LangPortuguese: "Download concluído",
		state.LangChinese:    "下载完成",
		state.LangJapanese:   "ダウンロード完了",
		state.LangItalian:    "Download completato",
		state.LangRussian:    "Загрузка завершена",
	},
	"dl.error": {
		state.LangEnglish:    "Error",
		state.LangTurkish:    "Hata",
		state.LangSpanish:    "Error",
		state.LangGerman:     "Fehler",
		state.LangFrench:     "Erreur",
		state.LangArabic:     "خطأ",
		state.LangPortuguese: "Erro",
		state.LangChinese:    "错误",
		state.LangJapanese:   "エラー",
		state.LangItalian:    "Errore",
		state.LangRussian:    "Ошибка",
	},
	"dl.no_logs": {
		state.LangEnglish:    "No logs",
		state.LangTurkish:    "Kayıt yok",
		state.LangSpanish:    "Sin registros",
		state.LangGerman:     "Keine Protokolle",
		state.LangFrench:     "Aucun journal",
		state.LangArabic:     "لا توجد سجلات",
		state.LangPortuguese: "Sem registros",
		state.LangChinese:    "暂无日志",
		state.LangJapanese:   "ログなし",
		state.LangItalian:    "Nessun log",
		state.LangRussian:    "Нет журналов",
	},
	"dl.downloaded_n": {
		state.LangEnglish:    "Downloaded %d song(s)",
		state.LangTurkish:    "%d parça indirildi",
		state.LangSpanish:    "%d canción(es) descargada(s)",
		state.LangGerman:     "%d Song(s) heruntergeladen",
		state.LangFrench:     "%d morceau(x) téléchargé(s)",
		state.LangArabic:     "تم تنزيل %d مقطع",
		state.LangPortuguese: "%d música(s) baixada(s)",
		state.LangChinese:    "已下载 %d 首歌曲",
		state.LangJapanese:   "%d 曲をダウンロードしました",
		state.LangItalian:    "%d brano(i) scaricato(i)",
		state.LangRussian:    "Загружено песен: %d",
	},
	"dl.errors_n": {
		state.LangEnglish:    "completed with %d error(s)",
		state.LangTurkish:    "%d hata ile tamamlandı",
		state.LangSpanish:    "completado con %d error(es)",
		state.LangGerman:     "mit %d Fehler(n) abgeschlossen",
		state.LangFrench:     "terminé avec %d erreur(s)",
		state.LangArabic:     "اكتمل مع %d خطأ",
		state.LangPortuguese: "concluído com %d erro(s)",
		state.LangChinese:    "完成，但有 %d 个错误",
		state.LangJapanese:   "%d 件のエラーで完了",
		state.LangItalian:    "completato con %d errore(i)",
		state.LangRussian:    "завершено с ошибками: %d",
	},
	"dl.console": {
		state.LangEnglish:    "CONSOLE",
		state.LangTurkish:    "KONSOL",
		state.LangSpanish:    "CONSOLA",
		state.LangGerman:     "KONSOLE",
		state.LangFrench:     "CONSOLE",
		state.LangArabic:     "وحدة التحكم",
		state.LangPortuguese: "CONSOLE",
		state.LangChinese:    "控制台",
		state.LangJapanese:   "コンソール",
		state.LangItalian:    "CONSOLE",
		state.LangRussian:    "КОНСОЛЬ",
	},
	"dl.playlist_download": {
		state.LangEnglish:    "Playlist Download",
		state.LangTurkish:    "Playlist İndirme",
		state.LangSpanish:    "Descarga de lista",
		state.LangGerman:     "Playlist-Download",
		state.LangFrench:     "Téléchargement de playlist",
		state.LangArabic:     "تنزيل قائمة التشغيل",
		state.LangPortuguese: "Download de playlist",
		state.LangChinese:    "歌单下载",
		state.LangJapanese:   "プレイリストダウンロード",
		state.LangItalian:    "Download playlist",
		state.LangRussian:    "Загрузка плейлиста",
	},

	// ── Home ────────────────────────────────────────────────────
	"home.console": {
		state.LangEnglish:    "CONSOLE",
		state.LangTurkish:    "KONSOL",
		state.LangSpanish:    "CONSOLA",
		state.LangGerman:     "KONSOLE",
		state.LangFrench:     "CONSOLE",
		state.LangArabic:     "وحدة التحكم",
		state.LangPortuguese: "CONSOLE",
		state.LangChinese:    "控制台",
		state.LangJapanese:   "コンソール",
		state.LangItalian:    "CONSOLE",
		state.LangRussian:    "КОНСОЛЬ",
	},
	"home.spectrum": {
		state.LangEnglish:    "SPECTRUM",
		state.LangTurkish:    "SPEKTRUM",
		state.LangSpanish:    "ESPECTRO",
		state.LangGerman:     "SPEKTRUM",
		state.LangFrench:     "SPECTRE",
		state.LangArabic:     "الطيف",
		state.LangPortuguese: "ESPECTRO",
		state.LangChinese:    "频谱",
		state.LangJapanese:   "スペクトラム",
		state.LangItalian:    "SPETTRO",
		state.LangRussian:    "СПЕКТР",
	},
	"home.songs": {
		state.LangEnglish:    "SONGS",
		state.LangTurkish:    "ŞARKILAR",
		state.LangSpanish:    "CANCIONES",
		state.LangGerman:     "LIEDER",
		state.LangFrench:     "MORCEAUX",
		state.LangArabic:     "الأغاني",
		state.LangPortuguese: "MÚSICAS",
		state.LangChinese:    "歌曲",
		state.LangJapanese:   "曲",
		state.LangItalian:    "BRANI",
		state.LangRussian:    "ПЕСНИ",
	},
	"home.title": {
		state.LangEnglish:    "Title",
		state.LangTurkish:    "Başlık",
		state.LangSpanish:    "Título",
		state.LangGerman:     "Titel",
		state.LangFrench:     "Titre",
		state.LangArabic:     "العنوان",
		state.LangPortuguese: "Título",
		state.LangChinese:    "标题",
		state.LangJapanese:   "タイトル",
		state.LangItalian:    "Titolo",
		state.LangRussian:    "Название",
	},
	"home.artist": {
		state.LangEnglish:    "Artist",
		state.LangTurkish:    "Sanatçı",
		state.LangSpanish:    "Artista",
		state.LangGerman:     "Künstler",
		state.LangFrench:     "Artiste",
		state.LangArabic:     "الفنان",
		state.LangPortuguese: "Artista",
		state.LangChinese:    "艺术家",
		state.LangJapanese:   "アーティスト",
		state.LangItalian:    "Artista",
		state.LangRussian:    "Исполнитель",
	},
	"home.duration": {
		state.LangEnglish:    "Duration",
		state.LangTurkish:    "Süre",
		state.LangSpanish:    "Duración",
		state.LangGerman:     "Dauer",
		state.LangFrench:     "Durée",
		state.LangArabic:     "المدة",
		state.LangPortuguese: "Duração",
		state.LangChinese:    "时长",
		state.LangJapanese:   "再生時間",
		state.LangItalian:    "Durata",
		state.LangRussian:    "Длительность",
	},
	"home.dur_short": {
		state.LangEnglish:    "Dur.",
		state.LangTurkish:    "Süre",
		state.LangSpanish:    "Dur.",
		state.LangGerman:     "Dauer",
		state.LangFrench:     "Durée",
		state.LangArabic:     "المدة",
		state.LangPortuguese: "Dur.",
		state.LangChinese:    "时长",
		state.LangJapanese:   "時間",
		state.LangItalian:    "Dur.",
		state.LangRussian:    "Длит.",
	},
	"home.operations": {
		state.LangEnglish:    "Operations",
		state.LangTurkish:    "İşlemler",
		state.LangSpanish:    "Operaciones",
		state.LangGerman:     "Aktionen",
		state.LangFrench:     "Opérations",
		state.LangArabic:     "العمليات",
		state.LangPortuguese: "Operações",
		state.LangChinese:    "操作",
		state.LangJapanese:   "操作",
		state.LangItalian:    "Operazioni",
		state.LangRussian:    "Действия",
	},
	"home.playlist": {
		state.LangEnglish:    "PLAYLIST",
		state.LangTurkish:    "ÇALMA LİSTESİ",
		state.LangSpanish:    "LISTA",
		state.LangGerman:     "PLAYLIST",
		state.LangFrench:     "PLAYLIST",
		state.LangArabic:     "قائمة التشغيل",
		state.LangPortuguese: "PLAYLIST",
		state.LangChinese:    "播放列表",
		state.LangJapanese:   "プレイリスト",
		state.LangItalian:    "PLAYLIST",
		state.LangRussian:    "ПЛЕЙЛИСТ",
	},
	"home.created": {
		state.LangEnglish:    "Created: ",
		state.LangTurkish:    "Oluşturma: ",
		state.LangSpanish:    "Creada: ",
		state.LangGerman:     "Erstellt: ",
		state.LangFrench:     "Créée : ",
		state.LangArabic:     "تاريخ الإنشاء: ",
		state.LangPortuguese: "Criada em: ",
		state.LangChinese:    "创建时间：",
		state.LangJapanese:   "作成日: ",
		state.LangItalian:    "Creata: ",
		state.LangRussian:    "Создан: ",
	},
	"home.import_failed": {
		state.LangEnglish:    "Import failed: ",
		state.LangTurkish:    "İçe aktarma başarısız: ",
		state.LangSpanish:    "Error al importar: ",
		state.LangGerman:     "Import fehlgeschlagen: ",
		state.LangFrench:     "Échec de l'import : ",
		state.LangArabic:     "فشل الاستيراد: ",
		state.LangPortuguese: "Falha ao importar: ",
		state.LangChinese:    "导入失败：",
		state.LangJapanese:   "インポート失敗: ",
		state.LangItalian:    "Importazione fallita: ",
		state.LangRussian:    "Ошибка импорта: ",
	},
	"home.imported": {
		state.LangEnglish:    "Imported: ",
		state.LangTurkish:    "İçe aktarıldı: ",
		state.LangSpanish:    "Importado: ",
		state.LangGerman:     "Importiert: ",
		state.LangFrench:     "Importé : ",
		state.LangArabic:     "تم الاستيراد: ",
		state.LangPortuguese: "Importado: ",
		state.LangChinese:    "已导入：",
		state.LangJapanese:   "インポート済み: ",
		state.LangItalian:    "Importato: ",
		state.LangRussian:    "Импортировано: ",
	},
	"home.updated": {
		state.LangEnglish:    "Updated: ",
		state.LangTurkish:    "Güncellendi: ",
		state.LangSpanish:    "Actualizado: ",
		state.LangGerman:     "Aktualisiert: ",
		state.LangFrench:     "Mis à jour : ",
		state.LangArabic:     "تم التحديث: ",
		state.LangPortuguese: "Atualizado: ",
		state.LangChinese:    "已更新：",
		state.LangJapanese:   "更新済み: ",
		state.LangItalian:    "Aggiornato: ",
		state.LangRussian:    "Обновлено: ",
	},
	"home.update_failed": {
		state.LangEnglish:    "Update failed: ",
		state.LangTurkish:    "Güncelleme başarısız: ",
		state.LangSpanish:    "Error al actualizar: ",
		state.LangGerman:     "Aktualisierung fehlgeschlagen: ",
		state.LangFrench:     "Échec de la mise à jour : ",
		state.LangArabic:     "فشل التحديث: ",
		state.LangPortuguese: "Falha ao atualizar: ",
		state.LangChinese:    "更新失败：",
		state.LangJapanese:   "更新失敗: ",
		state.LangItalian:    "Aggiornamento fallito: ",
		state.LangRussian:    "Ошибка обновления: ",
	},
	"home.deleted": {
		state.LangEnglish:    "Deleted: ",
		state.LangTurkish:    "Silindi: ",
		state.LangSpanish:    "Eliminado: ",
		state.LangGerman:     "Gelöscht: ",
		state.LangFrench:     "Supprimé : ",
		state.LangArabic:     "تم الحذف: ",
		state.LangPortuguese: "Excluído: ",
		state.LangChinese:    "已删除：",
		state.LangJapanese:   "削除済み: ",
		state.LangItalian:    "Eliminato: ",
		state.LangRussian:    "Удалено: ",
	},
	"home.delete_failed": {
		state.LangEnglish:    "Delete failed: ",
		state.LangTurkish:    "Silme başarısız: ",
		state.LangSpanish:    "Error al eliminar: ",
		state.LangGerman:     "Löschen fehlgeschlagen: ",
		state.LangFrench:     "Échec de la suppression : ",
		state.LangArabic:     "فشل الحذف: ",
		state.LangPortuguese: "Falha ao excluir: ",
		state.LangChinese:    "删除失败：",
		state.LangJapanese:   "削除失敗: ",
		state.LangItalian:    "Eliminazione fallita: ",
		state.LangRussian:    "Ошибка удаления: ",
	},
	"home.playlist_renamed": {
		state.LangEnglish:    "Playlist renamed: ",
		state.LangTurkish:    "Playlist yeniden adlandırıldı: ",
		state.LangSpanish:    "Lista renombrada: ",
		state.LangGerman:     "Playlist umbenannt: ",
		state.LangFrench:     "Playlist renommée : ",
		state.LangArabic:     "تمت إعادة تسمية القائمة: ",
		state.LangPortuguese: "Playlist renomeada: ",
		state.LangChinese:    "歌单已重命名：",
		state.LangJapanese:   "プレイリスト名を変更: ",
		state.LangItalian:    "Playlist rinominata: ",
		state.LangRussian:    "Плейлист переименован: ",
	},
	"home.play_all": {
		state.LangEnglish:    "> Play All",
		state.LangTurkish:    "> Tümünü Oynat",
		state.LangSpanish:    "> Reproducir todo",
		state.LangGerman:     "> Alle abspielen",
		state.LangFrench:     "> Tout lire",
		state.LangArabic:     "> تشغيل الكل",
		state.LangPortuguese: "> Tocar tudo",
		state.LangChinese:    "> 播放全部",
		state.LangJapanese:   "> すべて再生",
		state.LangItalian:    "> Riproduci tutto",
		state.LangRussian:    "> Играть всё",
	},
	"home.shuffle": {
		state.LangEnglish:    "# Shuffle",
		state.LangTurkish:    "# Karıştır",
		state.LangSpanish:    "# Aleatorio",
		state.LangGerman:     "# Zufällig",
		state.LangFrench:     "# Aléatoire",
		state.LangArabic:     "# عشوائي",
		state.LangPortuguese: "# Aleatório",
		state.LangChinese:    "# 随机播放",
		state.LangJapanese:   "# シャッフル",
		state.LangItalian:    "# Casuale",
		state.LangRussian:    "# Перемешать",
	},

	// ── Profile ─────────────────────────────────────────────────
	"profile.saved": {
		state.LangEnglish:    "  v Saved!",
		state.LangTurkish:    "  v Kaydedildi!",
		state.LangSpanish:    "  v ¡Guardado!",
		state.LangGerman:     "  v Gespeichert!",
		state.LangFrench:     "  v Enregistré !",
		state.LangArabic:     "  v تم الحفظ!",
		state.LangPortuguese: "  v Salvo!",
		state.LangChinese:    "  v 已保存！",
		state.LangJapanese:   "  v 保存しました！",
		state.LangItalian:    "  v Salvato!",
		state.LangRussian:    "  v Сохранено!",
	},
	"profile.title": {
		state.LangEnglish:    "Profile",
		state.LangTurkish:    "Profil",
		state.LangSpanish:    "Perfil",
		state.LangGerman:     "Profil",
		state.LangFrench:     "Profil",
		state.LangArabic:     "الملف الشخصي",
		state.LangPortuguese: "Perfil",
		state.LangChinese:    "个人资料",
		state.LangJapanese:   "プロフィール",
		state.LangItalian:    "Profilo",
		state.LangRussian:    "Профиль",
	},
	"profile.save": {
		state.LangEnglish:    "  Save Profile  ",
		state.LangTurkish:    "  Profili Kaydet  ",
		state.LangSpanish:    "  Guardar perfil  ",
		state.LangGerman:     "  Profil speichern  ",
		state.LangFrench:     "  Enregistrer le profil  ",
		state.LangArabic:     "  حفظ الملف الشخصي  ",
		state.LangPortuguese: "  Salvar perfil  ",
		state.LangChinese:    "  保存个人资料  ",
		state.LangJapanese:   "  プロフィールを保存  ",
		state.LangItalian:    "  Salva profilo  ",
		state.LangRussian:    "  Сохранить профиль  ",
	},
	"profile.settings": {
		state.LangEnglish:    " Profile Settings",
		state.LangTurkish:    " Profil Ayarları",
		state.LangSpanish:    " Ajustes de perfil",
		state.LangGerman:     " Profileinstellungen",
		state.LangFrench:     " Paramètres du profil",
		state.LangArabic:     " إعدادات الملف الشخصي",
		state.LangPortuguese: " Configurações de perfil",
		state.LangChinese:    " 个人资料设置",
		state.LangJapanese:   " プロフィール設定",
		state.LangItalian:    " Impostazioni profilo",
		state.LangRussian:    " Настройки профиля",
	},

	// ── Playlist ────────────────────────────────────────────────
	"pl.art_selected": {
		state.LangEnglish:    "Art selected",
		state.LangTurkish:    "Resim seçildi",
		state.LangSpanish:    "Imagen seleccionada",
		state.LangGerman:     "Bild ausgewählt",
		state.LangFrench:     "Image sélectionnée",
		state.LangArabic:     "تم اختيار الصورة",
		state.LangPortuguese: "Imagem selecionada",
		state.LangChinese:    "已选择图片",
		state.LangJapanese:   "画像を選択しました",
		state.LangItalian:    "Immagine selezionata",
		state.LangRussian:    "Обложка выбрана",
	},
	"pl.img_size": {
		state.LangEnglish:    "Image must be under 1MB",
		state.LangTurkish:    "Resim 1MB altında olmalı",
		state.LangSpanish:    "La imagen debe ser menor de 1MB",
		state.LangGerman:     "Bild muss unter 1MB sein",
		state.LangFrench:     "L'image doit faire moins de 1 Mo",
		state.LangArabic:     "يجب أن تكون الصورة أقل من 1MB",
		state.LangPortuguese: "A imagem deve ter menos de 1MB",
		state.LangChinese:    "图片必须小于1MB",
		state.LangJapanese:   "画像は1MB未満にしてください",
		state.LangItalian:    "L'immagine deve essere sotto 1MB",
		state.LangRussian:    "Изображение должно быть меньше 1MB",
	},
	"pl.img_reset": {
		state.LangEnglish:    "Image reset",
		state.LangTurkish:    "Resim sıfırlandı",
		state.LangSpanish:    "Imagen restablecida",
		state.LangGerman:     "Bild zurückgesetzt",
		state.LangFrench:     "Image réinitialisée",
		state.LangArabic:     "تمت إعادة تعيين الصورة",
		state.LangPortuguese: "Imagem redefinida",
		state.LangChinese:    "图片已重置",
		state.LangJapanese:   "画像をリセットしました",
		state.LangItalian:    "Immagine reimpostata",
		state.LangRussian:    "Обложка сброшена",
	},
	"pl.no_profile": {
		state.LangEnglish:    "No profile",
		state.LangTurkish:    "Profil yok",
		state.LangSpanish:    "Sin perfil",
		state.LangGerman:     "Kein Profil",
		state.LangFrench:     "Aucun profil",
		state.LangArabic:     "لا يوجد ملف شخصي",
		state.LangPortuguese: "Sem perfil",
		state.LangChinese:    "无个人资料",
		state.LangJapanese:   "プロフィールなし",
		state.LangItalian:    "Nessun profilo",
		state.LangRussian:    "Нет профиля",
	},
	"pl.name_required": {
		state.LangEnglish:    "Name is required",
		state.LangTurkish:    "İsim gerekli",
		state.LangSpanish:    "El nombre es obligatorio",
		state.LangGerman:     "Name ist erforderlich",
		state.LangFrench:     "Le nom est requis",
		state.LangArabic:     "الاسم مطلوب",
		state.LangPortuguese: "Nome é obrigatório",
		state.LangChinese:    "名称为必填项",
		state.LangJapanese:   "名前は必須です",
		state.LangItalian:    "Il nome è obbligatorio",
		state.LangRussian:    "Требуется имя",
	},
	"pl.name_exists": {
		state.LangEnglish:    "Name already exists",
		state.LangTurkish:    "Bu isim zaten var",
		state.LangSpanish:    "El nombre ya existe",
		state.LangGerman:     "Name existiert bereits",
		state.LangFrench:     "Ce nom existe déjà",
		state.LangArabic:     "هذا الاسم موجود بالفعل",
		state.LangPortuguese: "Este nome já existe",
		state.LangChinese:    "该名称已存在",
		state.LangJapanese:   "その名前は既に存在します",
		state.LangItalian:    "Nome già esistente",
		state.LangRussian:    "Такое имя уже существует",
	},
	"pl.created": {
		state.LangEnglish:    "Playlist created!",
		state.LangTurkish:    "Playlist oluşturuldu!",
		state.LangSpanish:    "¡Lista creada!",
		state.LangGerman:     "Playlist erstellt!",
		state.LangFrench:     "Playlist créée !",
		state.LangArabic:     "تم إنشاء القائمة!",
		state.LangPortuguese: "Playlist criada!",
		state.LangChinese:    "歌单已创建！",
		state.LangJapanese:   "プレイリストを作成しました！",
		state.LangItalian:    "Playlist creata!",
		state.LangRussian:    "Плейлист создан!",
	},
	"pl.saved": {
		state.LangEnglish:    "Saved!",
		state.LangTurkish:    "Kaydedildi!",
		state.LangSpanish:    "¡Guardado!",
		state.LangGerman:     "Gespeichert!",
		state.LangFrench:     "Enregistré !",
		state.LangArabic:     "تم الحفظ!",
		state.LangPortuguese: "Salvo!",
		state.LangChinese:    "已保存！",
		state.LangJapanese:   "保存しました！",
		state.LangItalian:    "Salvato!",
		state.LangRussian:    "Сохранено!",
	},
	"pl.select_art": {
		state.LangEnglish:    "Select Art Image",
		state.LangTurkish:    "Resim Seç",
		state.LangSpanish:    "Seleccionar imagen",
		state.LangGerman:     "Bild auswählen",
		state.LangFrench:     "Choisir une image",
		state.LangArabic:     "اختر صورة",
		state.LangPortuguese: "Selecionar imagem",
		state.LangChinese:    "选择封面图片",
		state.LangJapanese:   "画像を選択",
		state.LangItalian:    "Seleziona immagine",
		state.LangRussian:    "Выбрать обложку",
	},
	"pl.img_files": {
		state.LangEnglish:    "Image Files",
		state.LangTurkish:    "Resim Dosyaları",
		state.LangSpanish:    "Archivos de imagen",
		state.LangGerman:     "Bilddateien",
		state.LangFrench:     "Fichiers image",
		state.LangArabic:     "ملفات الصور",
		state.LangPortuguese: "Arquivos de imagem",
		state.LangChinese:    "图片文件",
		state.LangJapanese:   "画像ファイル",
		state.LangItalian:    "File immagine",
		state.LangRussian:    "Файлы изображений",
	},
	"pl.deleted": {
		state.LangEnglish:    "Deleted",
		state.LangTurkish:    "Silindi",
		state.LangSpanish:    "Eliminado",
		state.LangGerman:     "Gelöscht",
		state.LangFrench:     "Supprimé",
		state.LangArabic:     "تم الحذف",
		state.LangPortuguese: "Excluído",
		state.LangChinese:    "已删除",
		state.LangJapanese:   "削除済み",
		state.LangItalian:    "Eliminato",
		state.LangRussian:    "Удалено",
	},
	"pl.no_playlists": {
		state.LangEnglish:    "No playlists",
		state.LangTurkish:    "Playlist yok",
		state.LangSpanish:    "Sin listas",
		state.LangGerman:     "Keine Playlists",
		state.LangFrench:     "Aucune playlist",
		state.LangArabic:     "لا توجد قوائم تشغيل",
		state.LangPortuguese: "Sem playlists",
		state.LangChinese:    "无歌单",
		state.LangJapanese:   "プレイリストなし",
		state.LangItalian:    "Nessuna playlist",
		state.LangRussian:    "Нет плейлистов",
	},
	"pl.playlists_title": {
		state.LangEnglish:    " Playlists",
		state.LangTurkish:    " Playlistler",
		state.LangSpanish:    " Listas",
		state.LangGerman:     " Playlists",
		state.LangFrench:     " Playlists",
		state.LangArabic:     " قوائم التشغيل",
		state.LangPortuguese: " Playlists",
		state.LangChinese:    " 歌单",
		state.LangJapanese:   " プレイリスト",
		state.LangItalian:    " Playlist",
		state.LangRussian:    " Плейлисты",
	},
	"pl.new_prefix": {
		state.LangEnglish:    " New Playlist",
		state.LangTurkish:    " Yeni Playlist",
		state.LangSpanish:    " Nueva lista",
		state.LangGerman:     " Neue Playlist",
		state.LangFrench:     " Nouvelle playlist",
		state.LangArabic:     " قائمة جديدة",
		state.LangPortuguese: " Nova playlist",
		state.LangChinese:    " 新歌单",
		state.LangJapanese:   " 新しいプレイリスト",
		state.LangItalian:    " Nuova playlist",
		state.LangRussian:    " Новый плейлист",
	},
	"pl.creating_new": {
		state.LangEnglish:    "(creating new)",
		state.LangTurkish:    "(yeni oluşturuluyor)",
		state.LangSpanish:    "(creando nueva)",
		state.LangGerman:     "(neu wird erstellt)",
		state.LangFrench:     "(création en cours)",
		state.LangArabic:     "(جارٍ الإنشاء)",
		state.LangPortuguese: "(criando nova)",
		state.LangChinese:    "（正在新建）",
		state.LangJapanese:   "（新規作成中）",
		state.LangItalian:    "(creazione in corso)",
		state.LangRussian:    "(создание)",
	},
	"pl.click_select": {
		state.LangEnglish:    "(click to select image)",
		state.LangTurkish:    "(dosya seçmek için tıkla)",
		state.LangSpanish:    "(clic para seleccionar imagen)",
		state.LangGerman:     "(klicken um Bild zu wählen)",
		state.LangFrench:     "(cliquer pour choisir une image)",
		state.LangArabic:     "(انقر لاختيار صورة)",
		state.LangPortuguese: "(clique para selecionar imagem)",
		state.LangChinese:    "（点击选择图片）",
		state.LangJapanese:   "（クリックで画像を選択）",
		state.LangItalian:    "(clicca per selezionare)",
		state.LangRussian:    "(нажмите чтобы выбрать)",
	},
	"pl.save": {
		state.LangEnglish:    "  Save  ",
		state.LangTurkish:    "  Kaydet  ",
		state.LangSpanish:    "  Guardar  ",
		state.LangGerman:     "  Speichern  ",
		state.LangFrench:     "  Enregistrer  ",
		state.LangArabic:     "  حفظ  ",
		state.LangPortuguese: "  Salvar  ",
		state.LangChinese:    "  保存  ",
		state.LangJapanese:   "  保存  ",
		state.LangItalian:    "  Salva  ",
		state.LangRussian:    "  Сохранить  ",
	},
	"pl.create": {
		state.LangEnglish:    "  Create  ",
		state.LangTurkish:    "  Oluştur  ",
		state.LangSpanish:    "  Crear  ",
		state.LangGerman:     "  Erstellen  ",
		state.LangFrench:     "  Créer  ",
		state.LangArabic:     "  إنشاء  ",
		state.LangPortuguese: "  Criar  ",
		state.LangChinese:    "  创建  ",
		state.LangJapanese:   "  作成  ",
		state.LangItalian:    "  Crea  ",
		state.LangRussian:    "  Создать  ",
	},
	"pl.delete_btn": {
		state.LangEnglish:    "  Delete Playlist  ",
		state.LangTurkish:    "  Playlist Sil  ",
		state.LangSpanish:    "  Eliminar lista  ",
		state.LangGerman:     "  Playlist löschen  ",
		state.LangFrench:     "  Supprimer la playlist  ",
		state.LangArabic:     "  حذف القائمة  ",
		state.LangPortuguese: "  Excluir playlist  ",
		state.LangChinese:    "  删除歌单  ",
		state.LangJapanese:   "  プレイリスト削除  ",
		state.LangItalian:    "  Elimina playlist  ",
		state.LangRussian:    "  Удалить плейлист  ",
	},
	"pl.add_btn": {
		state.LangEnglish:    "  Add Playlist  ",
		state.LangTurkish:    "  Playlist Ekle  ",
		state.LangSpanish:    "  Añadir lista  ",
		state.LangGerman:     "  Playlist hinzufügen  ",
		state.LangFrench:     "  Ajouter une playlist  ",
		state.LangArabic:     "  إضافة قائمة  ",
		state.LangPortuguese: "  Adicionar playlist  ",
		state.LangChinese:    "  添加歌单  ",
		state.LangJapanese:   "  プレイリスト追加  ",
		state.LangItalian:    "  Aggiungi playlist  ",
		state.LangRussian:    "  Добавить плейлист  ",
	},
	"pl.reset_btn": {
		state.LangEnglish:    "  Reset Image  ",
		state.LangTurkish:    "  Resmi Sıfırla  ",
		state.LangSpanish:    "  Restablecer imagen  ",
		state.LangGerman:     "  Bild zurücksetzen  ",
		state.LangFrench:     "  Réinitialiser l'image  ",
		state.LangArabic:     "  إعادة تعيين الصورة  ",
		state.LangPortuguese: "  Redefinir imagem  ",
		state.LangChinese:    "  重置图片  ",
		state.LangJapanese:   "  画像リセット  ",
		state.LangItalian:    "  Reimposta immagine  ",
		state.LangRussian:    "  Сбросить обложку  ",
	},
	"pl.settings_title": {
		state.LangEnglish:    " Playlist Settings",
		state.LangTurkish:    " Playlist Ayarları",
		state.LangSpanish:    " Ajustes de lista",
		state.LangGerman:     " Playlist-Einstellungen",
		state.LangFrench:     " Paramètres playlist",
		state.LangArabic:     " إعدادات القائمة",
		state.LangPortuguese: " Configurações de playlist",
		state.LangChinese:    " 歌单设置",
		state.LangJapanese:   " プレイリスト設定",
		state.LangItalian:    " Impostazioni playlist",
		state.LangRussian:    " Настройки плейлиста",
	},

	// ── Setup / welcome ───────────────────────────────────────────
	"setup.welcome": {
		state.LangEnglish:    "Welcome",
		state.LangTurkish:    "Hoş Geldiniz",
		state.LangSpanish:    "Bienvenido",
		state.LangGerman:     "Willkommen",
		state.LangFrench:     "Bienvenue",
		state.LangArabic:     "مرحباً",
		state.LangPortuguese: "Bem-vindo",
		state.LangChinese:    "欢迎",
		state.LangJapanese:   "ようこそ",
		state.LangItalian:    "Benvenuto",
		state.LangRussian:    "Добро пожаловать",
	},
	"setup.hint": {
		state.LangEnglish:    "[↑↓] Change  [Enter] Confirm",
		state.LangTurkish:    "[↑↓] Değiştir  [Enter] Onayla",
		state.LangSpanish:    "[↑↓] Cambiar  [Enter] Confirmar",
		state.LangGerman:     "[↑↓] Ändern  [Enter] Bestätigen",
		state.LangFrench:     "[↑↓] Changer  [Enter] Confirmer",
		state.LangArabic:     "[↑↓] تغيير  [Enter] تأكيد",
		state.LangPortuguese: "[↑↓] Alterar  [Enter] Confirmar",
		state.LangChinese:    "[↑↓] 更改  [Enter] 确认",
		state.LangJapanese:   "[↑↓] 変更  [Enter] 確定",
		state.LangItalian:    "[↑↓] Cambia  [Enter] Conferma",
		state.LangRussian:    "[↑↓] Изменить  [Enter] Подтвердить",
	},
	"setup.lang_title": {
		state.LangEnglish:    "Language / Dil:",
		state.LangTurkish:    "Dil / Language:",
		state.LangSpanish:    "Idioma:",
		state.LangGerman:     "Sprache:",
		state.LangFrench:     "Langue :",
		state.LangArabic:     "اللغة:",
		state.LangPortuguese: "Idioma:",
		state.LangChinese:    "语言：",
		state.LangJapanese:   "言語:",
		state.LangItalian:    "Lingua:",
		state.LangRussian:    "Язык:",
	},

	// ── Connect (browser connector) ───────────────────────────────
	"connect.title": {
		state.LangEnglish:    "Browser Connector — pick a platform   •   F1 to switch   •   Enter to confirm",
		state.LangTurkish:    "Tarayıcı Bağlayıcı — bir platform seçin   •   F1 ile geçiş   •   Enter ile onayla",
		state.LangSpanish:    "Conector del navegador — elige plataforma   •   F1 para cambiar   •   Enter para confirmar",
		state.LangGerman:     "Browser-Verbinder — Plattform wählen   •   F1 zum Wechseln   •   Enter zum Bestätigen",
		state.LangFrench:     "Connecteur navigateur — choisissez une plateforme   •   F1 pour changer   •   Entrée pour confirmer",
		state.LangArabic:     "موصل المتصفح — اختر منصة   •   F1 للتبديل   •   Enter للتأكيد",
		state.LangPortuguese: "Conector do navegador — escolha a plataforma   •   F1 para alternar   •   Enter para confirmar",
		state.LangChinese:    "浏览器连接器 — 选择平台   •   F1 切换   •   回车确认",
		state.LangJapanese:   "ブラウザ連携 — プラットフォームを選択   •   F1で切替   •   Enterで確定",
		state.LangItalian:    "Connettore browser — scegli una piattaforma   •   F1 per cambiare   •   Invio per confermare",
		state.LangRussian:    "Браузер-коннектор — выберите платформу   •   F1 переключить   •   Enter подтвердить",
	},
	"connect.footer": {
		state.LangEnglish:    "Keep the Spotify or YouTube Music tab open in your browser.",
		state.LangTurkish:    "Spotify veya YouTube Music sekmesini tarayıcıda açık tutun.",
		state.LangSpanish:    "Mantén abierta la pestaña de Spotify o YouTube Music.",
		state.LangGerman:     "Halten Sie den Spotify- oder YouTube-Music-Tab offen.",
		state.LangFrench:     "Gardez l'onglet Spotify ou YouTube Music ouvert.",
		state.LangArabic:     "أبقِ تبويب سبوتيفاي أو يوتيوب ميوزك مفتوحاً.",
		state.LangPortuguese: "Mantenha a aba do Spotify ou YouTube Music aberta.",
		state.LangChinese:    "请在浏览器中保持 Spotify 或 YouTube Music 标签页打开。",
		state.LangJapanese:   "ブラウザでSpotifyまたはYouTube Musicのタブを開いたままにしてください。",
		state.LangItalian:    "Tieni aperta la scheda Spotify o YouTube Music.",
		state.LangRussian:    "Держите вкладку Spotify или YouTube Music открытой.",
	},
	"connect.conn_error": {
		state.LangEnglish:    "Connection error",
		state.LangTurkish:    "Bağlantı hatası",
		state.LangSpanish:    "Error de conexión",
		state.LangGerman:     "Verbindungsfehler",
		state.LangFrench:     "Erreur de connexion",
		state.LangArabic:     "خطأ في الاتصال",
		state.LangPortuguese: "Erro de conexão",
		state.LangChinese:    "连接错误",
		state.LangJapanese:   "接続エラー",
		state.LangItalian:    "Errore di connessione",
		state.LangRussian:    "Ошибка соединения",
	},
	"connect.esc_close": {
		state.LangEnglish:    "Close with Esc",
		state.LangTurkish:    "Esc ile kapat",
		state.LangSpanish:    "Cerrar con Esc",
		state.LangGerman:     "Mit Esc schließen",
		state.LangFrench:     "Fermer avec Échap",
		state.LangArabic:     "أغلق بزر Esc",
		state.LangPortuguese: "Fechar com Esc",
		state.LangChinese:    "按 Esc 关闭",
		state.LangJapanese:   "Escで閉じる",
		state.LangItalian:    "Chiudi con Esc",
		state.LangRussian:    "Закрыть через Esc",
	},
	"connect.fetching": {
		state.LangEnglish:    "Fetching browser info...",
		state.LangTurkish:    "Tarayıcı bilgisi alınıyor...",
		state.LangSpanish:    "Obteniendo info del navegador...",
		state.LangGerman:     "Browser-Info wird abgerufen...",
		state.LangFrench:     "Récupération des infos...",
		state.LangArabic:     "جارٍ جلب معلومات المتصفح...",
		state.LangPortuguese: "Buscando info do navegador...",
		state.LangChinese:    "正在获取浏览器信息…",
		state.LangJapanese:   "ブラウザ情報を取得中...",
		state.LangItalian:    "Recupero info browser...",
		state.LangRussian:    "Получение данных браузера...",
	},
	"connect.scanning": {
		state.LangEnglish:    "scanning...",
		state.LangTurkish:    "taranıyor...",
		state.LangSpanish:    "analizando...",
		state.LangGerman:     "wird gescannt...",
		state.LangFrench:     "analyse...",
		state.LangArabic:     "جارٍ الفحص...",
		state.LangPortuguese: "analisando...",
		state.LangChinese:    "扫描中…",
		state.LangJapanese:   "スキャン中...",
		state.LangItalian:    "scansione...",
		state.LangRussian:    "сканирование...",
	},
	"connect.found": {
		state.LangEnglish:    "%s — %d playlists found",
		state.LangTurkish:    "%s — %d playlist bulundu",
		state.LangSpanish:    "%s — %d listas encontradas",
		state.LangGerman:     "%s — %d Playlists gefunden",
		state.LangFrench:     "%s — %d playlists trouvées",
		state.LangArabic:     "%s — تم العثور على %d قائمة",
		state.LangPortuguese: "%s — %d playlists encontradas",
		state.LangChinese:    "%s — 找到 %d 个歌单",
		state.LangJapanese:   "%s — %d 件のプレイリストが見つかりました",
		state.LangItalian:    "%s — %d playlist trovate",
		state.LangRussian:    "%s — найдено плейлистов: %d",
	},
	"connect.songs_count": {
		state.LangEnglish:    "(%d songs)",
		state.LangTurkish:    "(%d şarkı)",
		state.LangSpanish:    "(%d canciones)",
		state.LangGerman:     "(%d Lieder)",
		state.LangFrench:     "(%d morceaux)",
		state.LangArabic:     "(%d أغنية)",
		state.LangPortuguese: "(%d músicas)",
		state.LangChinese:    "（%d 首）",
		state.LangJapanese:   "（%d 曲）",
		state.LangItalian:    "(%d brani)",
		state.LangRussian:    "(песен: %d)",
	},
	"connect.confirmed": {
		state.LangEnglish:    "[Confirmed]",
		state.LangTurkish:    "[Onaylandı]",
		state.LangSpanish:    "[Confirmado]",
		state.LangGerman:     "[Bestätigt]",
		state.LangFrench:     "[Confirmé]",
		state.LangArabic:     "[تم التأكيد]",
		state.LangPortuguese: "[Confirmado]",
		state.LangChinese:    "[已确认]",
		state.LangJapanese:   "[確定済み]",
		state.LangItalian:    "[Confermato]",
		state.LangRussian:    "[Подтверждено]",
	},
	"connect.confirm": {
		state.LangEnglish:    " Confirm ",
		state.LangTurkish:    " Onayla ",
		state.LangSpanish:    " Confirmar ",
		state.LangGerman:     " Bestätigen ",
		state.LangFrench:     " Confirmer ",
		state.LangArabic:     " تأكيد ",
		state.LangPortuguese: " Confirmar ",
		state.LangChinese:    " 确认 ",
		state.LangJapanese:   " 確定 ",
		state.LangItalian:    " Conferma ",
		state.LangRussian:    " Подтвердить ",
	},
	"connect.no_playlist_found": {
		state.LangEnglish:    "(no playlists found)",
		state.LangTurkish:    "(playlist bulunamadı)",
		state.LangSpanish:    "(no se encontraron listas)",
		state.LangGerman:     "(keine Playlists gefunden)",
		state.LangFrench:     "(aucune playlist trouvée)",
		state.LangArabic:     "(لم يتم العثور على قوائم)",
		state.LangPortuguese: "(nenhuma playlist encontrada)",
		state.LangChinese:    "（未找到歌单）",
		state.LangJapanese:   "（プレイリストなし）",
		state.LangItalian:    "(nessuna playlist trovata)",
		state.LangRussian:    "(плейлисты не найдены)",
	},
	"connect.save_error": {
		state.LangEnglish:    "Save error: %v",
		state.LangTurkish:    "Kayıt hatası: %v",
		state.LangSpanish:    "Error al guardar: %v",
		state.LangGerman:     "Speicherfehler: %v",
		state.LangFrench:     "Erreur d'enregistrement : %v",
		state.LangArabic:     "خطأ في الحفظ: %v",
		state.LangPortuguese: "Erro ao salvar: %v",
		state.LangChinese:    "保存错误：%v",
		state.LangJapanese:   "保存エラー: %v",
		state.LangItalian:    "Errore di salvataggio: %v",
		state.LangRussian:    "Ошибка сохранения: %v",
	},
	"connect.saved": {
		state.LangEnglish:    "Saved ✓  •  Enter/Esc to return",
		state.LangTurkish:    "Kaydedildi ✓  •  Enter/Esc ile ana ekrana dön",
		state.LangSpanish:    "Guardado ✓  •  Enter/Esc para volver",
		state.LangGerman:     "Gespeichert ✓  •  Enter/Esc zum Zurückkehren",
		state.LangFrench:     "Enregistré ✓  •  Entrée/Échap pour revenir",
		state.LangArabic:     "تم الحفظ ✓  •  Enter/Esc للعودة",
		state.LangPortuguese: "Salvo ✓  •  Enter/Esc para voltar",
		state.LangChinese:    "已保存 ✓  •  回车/Esc 返回",
		state.LangJapanese:   "保存しました ✓  •  Enter/Escで戻る",
		state.LangItalian:    "Salvato ✓  •  Invio/Esc per tornare",
		state.LangRussian:    "Сохранено ✓  •  Enter/Esc назад",
	},
	"connect.nav_hint": {
		state.LangEnglish:    "↑/↓ to navigate  •  Enter to confirm  •  Esc to go back",
		state.LangTurkish:    "↑/↓ ile gezin  •  Enter ile onayla  •  Esc ile geri",
		state.LangSpanish:    "↑/↓ para navegar  •  Enter para confirmar  •  Esc para volver",
		state.LangGerman:     "↑/↓ zum Navigieren  •  Enter zum Bestätigen  •  Esc zurück",
		state.LangFrench:     "↑/↓ pour naviguer  •  Entrée pour confirmer  •  Échap retour",
		state.LangArabic:     "↑/↓ للتنقل  •  Enter للتأكيد  •  Esc للرجوع",
		state.LangPortuguese: "↑/↓ para navegar  •  Enter para confirmar  •  Esc para voltar",
		state.LangChinese:    "↑/↓ 导航  •  回车确认  •  Esc 返回",
		state.LangJapanese:   "↑/↓で移動  •  Enterで確定  •  Escで戻る",
		state.LangItalian:    "↑/↓ per navigare  •  Invio per confermare  •  Esc indietro",
		state.LangRussian:    "↑/↓ навигация  •  Enter подтвердить  •  Esc назад",
	},

	// ── Player bar ────────────────────────────────────────────────
	"player.no_track": {
		state.LangEnglish:    "No track playing",
		state.LangTurkish:    "Çalan parça yok",
		state.LangSpanish:    "Ninguna canción en reproducción",
		state.LangGerman:     "Kein Titel läuft",
		state.LangFrench:     "Aucun morceau en lecture",
		state.LangArabic:     "لا يوجد مقطع قيد التشغيل",
		state.LangPortuguese: "Nenhuma faixa tocando",
		state.LangChinese:    "当前没有播放",
		state.LangJapanese:   "再生中の曲なし",
		state.LangItalian:    "Nessun brano in riproduzione",
		state.LangRussian:    "Ничего не играет",
	},
}
